fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
gentie: ## Your gentie_productKey, e.g. fc799538c7ad4cf5a5a0c2877a90cbd7
google_search: false ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: false ## If you want to add list number to toc please set the value to true.
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

#using RGB color, drop #
main_background: fbfbfb
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: commonweal
    directory: 404.html
    icon: fa-heartbeat
#  - page: about
#   directory: about/
#   icon: fa-user
#  - page: RSS
#    directory: rss/
#    icon: fa-rss
hide_post_sidebar: true

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, recent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  # - title: goodman
  #   url: https://github.com/byoungd/goodman/
  # - title: byoungd
  #   url: https://github.com/user/byoungd/


timeline:
  - num: 1
    word: 2016/06/12-Start
  - num: 2
    word: 2017/5/20-XXX
  - num: 4
    word: More

# Static files
js: js
css: css

# Theme version
version: 1.0.4
